#Start page
GET http://localhost:8080
###

#Hämtar alla birds
GET http://localhost:8080/birds
###

#Hämtar specifik bird
GET http://localhost:8080/birds/(enter id)
###

#Skicka in en bird
POST http://localhost:8080/birds 
Content-Type: application/json

{
"name": "Ducky", "age": 60, "weight": 12, "sex": "male"
}
###

#Ändra en bird
PUT http://localhost:8080/birds/5d030221-bc94-4980-921f-dce24e8a1848
Content-Type: application/json

{
"name": "Duckina", "age": 24, "weight": 22, "sex": "female"
}
###

#Ta bort en bird
DELETE http://localhost:8080/birds/958ad761-44b2-482f-b65d-4eefd1866d2d

###